#!/usr/bin/env node
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { register } from 'tsx/esm/api';
import type { Field } from './field/field.js';

const unregister = register();

const SCHEMA_CANDIDATES = [
  'src/env.schema.ts',
  'src/config/env.schema.ts',
  'env.schema.ts',
];

const OUTPUT_FILENAME = 'environment-variables.generated.ts';

async function main() {
  const cwd = process.cwd();

  const schemaPath = SCHEMA_CANDIDATES
    .map((p) => resolve(cwd, p))
    .find((p) => existsSync(p));

  if (!schemaPath) {
    console.error(
      `✗ Could not find env.schema.ts. Looked in:\n` +
      SCHEMA_CANDIDATES.map((p) => `  - ${p}`).join('\n'),
    );
    process.exit(1);
  }

  console.log(`→ Loading schema from ${schemaPath}`);

  const mod = await import(pathToFileURL(schemaPath).href);
  const envSchema = mod.envSchema as Record<string, Field<unknown>> | undefined;

  if (!envSchema || typeof envSchema !== 'object') {
    console.error(`[X] ${schemaPath} does not export "envSchema"`);
    process.exit(1);
  }

  const outputPath = resolve(schemaPath, '..', OUTPUT_FILENAME);
  const content = generate(envSchema);
  writeFileSync(outputPath, content, 'utf8');

  console.log(`[V] Generated ${outputPath}`);

  unregister();
}

function tsType(field: Field<unknown>): string {
  switch (field.kind) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return `${tsType(field.item!)}[]`;
  }
}

function genProperty(key: string, field: Field<unknown>): string {
  const lines: string[] = [];

  if (field.kind === 'number') {
    lines.push(
      `  @Transform(({ value }) => value === undefined ? value : Number(value))`,
    );
  } else if (field.kind === 'boolean') {
    lines.push(
      `  @Transform(({ value }) => {`,
      `    if (value === 'true' || value === '1' || value === true) return true;`,
      `    if (value === 'false' || value === '0' || value === false) return false;`,
      `    return value;`,
      `  })`,
    );
  } else if (field.kind === 'array') {
    lines.push(
      `  @Transform(({ value }) =>`,
      `    typeof value === 'string'`,
      `      ? value.split(${JSON.stringify(field.separator)}).map((s) => s.trim()).filter(Boolean)`,
      `      : value,`,
      `  )`,
    );
  }

  if (field.optional) lines.push(`  @IsOptional()`);
  if (field.kind === 'string') {
    lines.push(`  @IsString()`);
    if (!field.optional) lines.push(`  @IsNotEmpty()`);
    if (field.values) lines.push(`  @IsIn(${JSON.stringify(field.values)})`);
  } else if (field.kind === 'number') {
    lines.push(`  @IsNumber()`);
    if (field.min != null) lines.push(`  @Min(${field.min})`);
    if (field.max != null) lines.push(`  @Max(${field.max})`);
  } else if (field.kind === 'boolean') {
    lines.push(`  @IsBoolean()`);
  } else if (field.kind === 'array') {
    lines.push(`  @IsArray()`);
    if (field.item?.kind === 'string') {
      lines.push(`  @IsString({ each: true })`);
      if (field.item.values) {
        lines.push(`  @IsIn(${JSON.stringify(field.item.values)}, { each: true })`);
      }
    }
  }

  lines.push(`  ${key}${field.optional ? '?' : '!'}: ${tsType(field)};`);
  return lines.join('\n');
}

function generate(schema: Record<string, Field<unknown>>): string {
  const header = `/* AUTO-GENERATED by @duckpicker/nest-config-kit. DO NOT EDIT. */
/* eslint-disable */
import { Transform } from 'class-transformer';
import { IsArray, IsBoolean, IsIn, IsNotEmpty, IsNumber, IsOptional, IsString, Max, Min } from 'class-validator';

export class EnvironmentVariables {
`;

  const body = Object.entries(schema)
    .map(([key, field]) => genProperty(key, field))
    .join('\n\n');

  return header + body + '\n}\n';
}

main().catch((err) => {
  console.error(err);
  unregister();
  process.exit(1);
});